import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ConvexClientProvider } from "@/components/common/convex-client-provider";
import { interSans } from "@/fonts";
import type { LayoutProps } from "@/types/common";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: {
    default: "Next.js Template",
    template: "%s ‹ Template",
  },
  description: "Generated by create next app",
  authors: [
    {
      name: "Vinicius Fernandes",
      url: "https://github.com/fernandes-vinicius",
    },
  ],
  twitter: {},
  robots: "index, follow",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${interSans.variable} font-sans antialiased`}>
        <NuqsAdapter>
          <ConvexClientProvider>
            <Toaster />
            {children}
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
